name: Publish Python ğŸ distributions ğŸ“¦ to PyPI

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: python -m unittest discover ./tests
      - name: update version
        run: python get_latest_version.py
      - name: install deployment dependancies
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == â€˜refs/heads/mainâ€™
        run: |
          pip install twine
          pip install pexpect
      - name: package module
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == â€˜refs/heads/mainâ€™
        run: python setup.py sdist
      - name: deploy to pypi
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == â€˜refs/heads/mainâ€™
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
